import '@/css/globals.css'
import { NavBar } from '@/components/navigation/NavBar'

import Header from '@/components/header/header'
import { Footer } from '@/components/footer/Footer'
 

 
export const metadata = {
  title: 'Astral Art',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body class="flex flex-col min-h-screen">
  <div class="flex-grow">
    <Header/>
    <NavBar/>
    {children}
  </div>
  <Footer />
</body>
    </html>
  )
}
