import '@/css/globals.css'
import { NavBar } from '@/components/navigation/NavBar'

import Header from '@/components/header/header'
 

 
export const metadata = {
  title: 'Astral Art',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <NavBar/>
        {children}</body>
    </html>
  )
}
